apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-doc
  description: test-doc
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-a
