site_name: 'demo-docs'
site_description: 'demo docs'

plugins:
  - techdocs-core

markdown_extensions:
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Test:
    - Test2: index.md
  - Second: second_page.md
